[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "dark"
primaryColor = "#22c55e"
backgroundColor = "#0b1220"
secondaryBackgroundColor = "#0f172a"
textColor = "#ffffff"
